import { ChangeDetectionStrategy, Component, signal, computed } from '@angular/core';
import { ProjectHero } from '../../molecules/project-hero/project-hero';
import { ProjectFilter, ProjectFilterType } from '../../molecules/project-filter/project-filter';
import { ProjectCard, ProjectInfo } from '../../molecules/project-card/project-card';
import { ProjectDetail } from '../../molecules/project-detail/project-detail';
import { RevealDirective } from '../../../core/directives/reveal.directive';

@Component({
  selector: 'app-project-gallery',
  imports: [ProjectHero, ProjectFilter, ProjectCard, ProjectDetail, RevealDirective],
  templateUrl: './project-gallery.html',
  styleUrl: './project-gallery.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProjectGallery {
  readonly activeFilter = signal<ProjectFilterType>('todos');
  readonly selectedProject = signal<ProjectInfo | null>(null);

  readonly filteredProjects = computed(() => {
    const filter = this.activeFilter();
    if (filter === 'todos') {
      return this.projects;
    }
    return this.projects.filter(p => p.type === filter);
  });

  onFilterChange(filter: ProjectFilterType): void {
    this.activeFilter.set(filter);
  }

  onProjectSelect(project: ProjectInfo): void {
    this.selectedProject.set(project);
  }

  onCloseDetail(): void {
    this.selectedProject.set(null);
  }

  readonly projects: ProjectInfo[] = [
    // ── Dínamos ──────────────────────────────────────────────────────────────
    {
      id: 'dinamo-1',
      name: 'Dínamo Artesanal #1',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_1/imagen_1-4.jpeg',
      imageAlt: 'Mesa dínamo artesanal #1 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-2',
      name: 'Dínamo Artesanal #2',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_1/imagen_1-5.jpeg',
      imageAlt: 'Mesa dínamo artesanal #2 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-3',
      name: 'Dínamo Artesanal #3',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_1/imagen_1-8.jpeg',
      imageAlt: 'Mesa dínamo artesanal #3 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-4',
      name: 'Dínamo Artesanal #4',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_1/imagen_1-10.jpeg',
      imageAlt: 'Mesa dínamo artesanal #4 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-5',
      name: 'Dínamo Artesanal #5',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_1/imagen_1-11.jpeg',
      imageAlt: 'Mesa dínamo artesanal #5 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-6',
      name: 'Dínamo Artesanal #6',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_1/imagen_1-15.jpeg',
      imageAlt: 'Mesa dínamo artesanal #6 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-7',
      name: 'Dínamo Artesanal #7',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_1/imagen_1-17.jpeg',
      imageAlt: 'Mesa dínamo artesanal #7 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-8',
      name: 'Dínamo Artesanal #8',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_2/imagen_2-1.jpeg',
      imageAlt: 'Mesa dínamo artesanal #8 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-9',
      name: 'Dínamo Artesanal #9',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-2.jpeg',
      imageAlt: 'Mesa dínamo artesanal #9 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-10',
      name: 'Dínamo Artesanal #10',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-5.jpeg',
      imageAlt: 'Mesa dínamo artesanal #10 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-11',
      name: 'Dínamo Artesanal #11',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-6.jpeg',
      imageAlt: 'Mesa dínamo artesanal #11 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-12',
      name: 'Dínamo Artesanal #12',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-10.jpeg',
      imageAlt: 'Mesa dínamo artesanal #12 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-13',
      name: 'Dínamo Artesanal #13',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-11.jpeg',
      imageAlt: 'Mesa dínamo artesanal #13 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-14',
      name: 'Dínamo Artesanal #14',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-12.jpeg',
      imageAlt: 'Mesa dínamo artesanal #14 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-15',
      name: 'Dínamo Artesanal #15',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-17.jpeg',
      imageAlt: 'Mesa dínamo artesanal #15 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-16',
      name: 'Dínamo Artesanal #16',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-18.jpeg',
      imageAlt: 'Mesa dínamo artesanal #16 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-17',
      name: 'Dínamo Artesanal #17',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-20.jpeg',
      imageAlt: 'Mesa dínamo artesanal #17 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-18',
      name: 'Dínamo Artesanal #18',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-21.jpeg',
      imageAlt: 'Mesa dínamo artesanal #18 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-19',
      name: 'Dínamo Artesanal #19',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-22.jpeg',
      imageAlt: 'Mesa dínamo artesanal #19 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    {
      id: 'dinamo-20',
      name: 'Dínamo Artesanal #20',
      type: 'dinamos',
      typeLabel: 'Dínamo',
      description: 'Mesa dínamo fabricada artesanalmente en madera de pino. Estructura robusta con superficie de juego de alta precisión.',
      image: 'assets/images/projects/carpeta_3/imagen_3-26.png',
      imageAlt: 'Mesa dínamo artesanal #20 fabricada en madera de pino',
      materials: ['Madera de pino', 'Acrílico', 'Sistema de aire', 'Herrajes galvanizados'],
      customization: 'Dimensiones personalizadas según el espacio del cliente, acabado en barniz natural y portadores laterales integrados.',
      designStory: 'Cada dínamo Imperial es construido a mano en nuestro taller, priorizando la solidez de la estructura y la fluidez de la superficie de juego.',
      result: 'Un dínamo de alto rendimiento que combina la calidez de la madera natural con la precisión técnica requerida para el juego profesional.',
    },
    // ── Billares ─────────────────────────────────────────────────────────────
    {
      id: 'billar-1',
      name: 'Billar Imperial #1',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_1/imagen_1-1.jpeg',
      imageAlt: 'Mesa de billar Imperial #1 en madera de pino con paño negro',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-2',
      name: 'Billar Imperial #2',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_1/imagen_1-3.jpeg',
      imageAlt: 'Mesa de billar Imperial #2 en madera de pino vista superior',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-3',
      name: 'Billar Imperial #3',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_1/imagen_1-12.jpeg',
      imageAlt: 'Mesa de billar Imperial #3 con tapa de ping-pong azul',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-4',
      name: 'Billar Imperial #4',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_2/imagen_2-4.jpeg',
      imageAlt: 'Mesa de billar Imperial #4 render en sala de lujo',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-5',
      name: 'Billar Imperial #5',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_2/imagen_2-5.jpeg',
      imageAlt: 'Mesa de billar Imperial #5 en madera de pino',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-6',
      name: 'Billar Imperial #6',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_3/imagen_3-4.jpeg',
      imageAlt: 'Mesa de billar Imperial #6 en madera de pino',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-7',
      name: 'Billar Imperial #7',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_3/imagen_3-7.jpeg',
      imageAlt: 'Mesa de billar Imperial #7 en madera de pino',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-8',
      name: 'Billar Imperial #8',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_3/imagen_3-15.jpeg',
      imageAlt: 'Mesa de billar Imperial #8 en madera de pino',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-9',
      name: 'Billar Imperial #9',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_3/imagen_3-19.jpeg',
      imageAlt: 'Mesa de billar Imperial #9 en madera de pino',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    {
      id: 'billar-10',
      name: 'Billar Imperial #10',
      type: 'billares',
      typeLabel: 'Billar',
      description: 'Mesa de billar multifuncional convertible fabricada en madera de pino natural. Estructura sólida con ruedas de desplazamiento y paño profesional.',
      image: 'assets/images/projects/carpeta_3/imagen_3-27.png',
      imageAlt: 'Mesa de billar Imperial #10 en madera de pino',
      materials: ['Madera de pino', 'Paño profesional', 'Ruedas nivelables', 'Herrajes de acero'],
      customization: 'Tapa convertible para ping-pong o comedor, paño en color a elección y dimensiones reglamentarias o personalizadas.',
      designStory: 'Diseñada para hogares que buscan entretenimiento sin sacrificar espacio. La estructura en pino natural aporta calidez y la tapa convertible multiplica la funcionalidad.',
      result: 'Una mesa que transforma cualquier ambiente en un espacio de juego profesional, con la flexibilidad de adaptarse a múltiples usos.',
    },
    // ── Juegos de Mesa ───────────────────────────────────────────────────────
    {
      id: 'juego-1',
      name: 'Juego de Mesa Imperial #1',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_1/imagen_1-2.jpeg',
      imageAlt: 'Mesa de juego Imperial #1 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-2',
      name: 'Juego de Mesa Imperial #2',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_1/imagen_1-6.jpeg',
      imageAlt: 'Mesa de juego Imperial #2 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-3',
      name: 'Juego de Mesa Imperial #3',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_1/imagen_1-7.jpeg',
      imageAlt: 'Mesa de juego Imperial #3 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-4',
      name: 'Juego de Mesa Imperial #4',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_1/imagen_1-9.jpeg',
      imageAlt: 'Mesa de juego Imperial #4 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-5',
      name: 'Juego de Mesa Imperial #5',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_1/imagen_1-13.jpeg',
      imageAlt: 'Mesa de juego Imperial #5 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-6',
      name: 'Juego de Mesa Imperial #6',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-6.jpeg',
      imageAlt: 'Mesa de juego Imperial #6 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-7',
      name: 'Juego de Mesa Imperial #7',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_2/imagen_2-2.jpeg',
      imageAlt: 'Mesa de juego Imperial #7 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-8',
      name: 'Juego de Mesa Imperial #8',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_2/imagen_2-3.jpeg',
      imageAlt: 'Mesa de juego Imperial #8 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-9',
      name: 'Juego de Mesa Imperial #9',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_2/imagen_2-6.png',
      imageAlt: 'Mesa de juego Imperial #9 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-10',
      name: 'Juego de Mesa Imperial #10',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-3.jpeg',
      imageAlt: 'Mesa de juego Imperial #10 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-11',
      name: 'Juego de Mesa Imperial #11',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-8.jpeg',
      imageAlt: 'Mesa de juego Imperial #11 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-12',
      name: 'Juego de Mesa Imperial #12',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-9.jpeg',
      imageAlt: 'Mesa de juego Imperial #12 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-13',
      name: 'Juego de Mesa Imperial #13',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-13.jpeg',
      imageAlt: 'Mesa de juego Imperial #13 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-14',
      name: 'Juego de Mesa Imperial #14',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-14.jpeg',
      imageAlt: 'Mesa de juego Imperial #14 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-15',
      name: 'Juego de Mesa Imperial #15',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-16.jpeg',
      imageAlt: 'Mesa de juego Imperial #15 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-16',
      name: 'Juego de Mesa Imperial #16',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-23.jpeg',
      imageAlt: 'Mesa de juego Imperial #16 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-17',
      name: 'Juego de Mesa Imperial #17',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-24.jpeg',
      imageAlt: 'Mesa de juego Imperial #17 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    },
    {
      id: 'juego-18',
      name: 'Juego de Mesa Imperial #18',
      type: 'juegos',
      typeLabel: 'Juego de Mesa',
      description: 'Mesa de juego artesanal fabricada en madera de pino. Diseño versátil para múltiples juegos de mesa y entretenimiento familiar.',
      image: 'assets/images/projects/carpeta_3/imagen_3-25.jpeg',
      imageAlt: 'Mesa de juego Imperial #18 artesanal en madera de pino',
      materials: ['Madera de pino', 'Tapizado interior', 'Herrajes de bronce', 'Acabado barnizado'],
      customization: 'Superficie personalizable, compartimentos para piezas y accesorios, y colores de tapizado a elección del cliente.',
      designStory: 'Fabricadas para reunir a familias y amigos en torno a sus juegos favoritos, con la calidad y durabilidad que caracteriza a Imperial Hockey Dinamos.',
      result: 'Mesas que se convierten en el centro de entretenimiento del hogar, diseñadas para durar generaciones.',
    }
  ];
}
